name: CI

on:
  push:

jobs:
  build-windows-x86_64-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: windows-x86_64/
  build-windows-arm64-rel:
    runs-on: [ windows, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A ARM64 -DCMAKE_UNITY_BUILD=ON -DENABLE_VK_IMPL=OFF -DENABLE_DX_IMPL=ON"
          config: "Release"
          bin-dir: "windows-arm64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-arm64
          path: windows-arm64/
  build-linux-x86_64-rel:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64
          path: linux-x86_64/
  build-macos-universal-rel:
    runs-on: [ macos, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: '-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_UNITY_BUILD=ON'
          config: "Release"
          bin-dir: "macos-universal"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal
          path: macos-universal/
  test-windows-x86_64-cpu:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          out-dir: "windows-x86_64-cpu-output"
          test-args: "--nogpu -j4"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-cpu-output
          path: windows-x86_64-cpu-output/
  test-windows-x86_64-gpu-nv:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          out-dir: "windows-x86_64-gpu-nv-output"
          test-args: "--device NV --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gpu-nv-output
          path: windows-x86_64-gpu-nv-output/
  test-windows-x86_64-gpu-amd:
    runs-on: [ windows, x86_64, amd ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          out-dir: "windows-x86_64-gpu-amd-output"
          test-args: "--device AMD --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gpu-amd-output
          path: windows-x86_64-gpu-amd-output/
  test-windows-x86_64-gpu-arc:
    runs-on: [ windows, x86_64, arc ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          out-dir: "windows-x86_64-gpu-arc-output"
          test-args: "--device Arc --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gpu-arc-output
          path: windows-x86_64-gpu-arc-output/
  test-windows-x86_64-gpu-xe:
    runs-on: [ windows, x86_64, xe ]
    needs:
      - build-windows-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64"
          out-dir: "windows-x86_64-gpu-xe-output"
          test-args: "--device Xe --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gpu-xe-output
          path: windows-x86_64-gpu-xe-output/
  test-windows-arm64-cpu:
    runs-on: [ windows, arm64 ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          out-dir: "windows-arm64-cpu-output"
          test-args: "--nogpu -j4"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-arm64-cpu-output
          path: windows-arm64-cpu-output/
  test-windows-arm64-gpu-adreno:
    runs-on: [ windows, arm64, adreno ]
    needs:
      - build-windows-arm64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-arm64"
          out-dir: "windows-arm64-gpu-adreno-output"
          test-args: "--device Adreno --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-arm64-gpu-adreno-output
          path: windows-arm64-gpu-adreno-output/
  test-linux-x86_64-cpu:
    runs-on: [ linux, x86_64 ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          out-dir: "linux-x86_64-cpu-output"
          test-args: "--nogpu -j4"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-cpu-output
          path: linux-x86_64-cpu-output/
  test-linux-x86_64-gpu-amd:
    runs-on: [ linux, x86_64, amd ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          out-dir: "linux-x86_64-gpu-amd-output"
          test-args: "--device AMD --nocpu --nohwrt"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-gpu-amd-output
          path: linux-x86_64-gpu-amd-output/
  test-linux-x86_64-gpu-nv:
    runs-on: [ linux, x86_64, nv ]
    needs:
      - build-linux-x86_64-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64"
          out-dir: "linux-x86_64-gpu-nv-output"
          test-args: "--device NV --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-gpu-nv-output
          path: linux-x86_64-gpu-nv-output/
  test-macos-arm64-cpu:
    runs-on: [ macos, arm64 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          out-dir: "macos-arm64-cpu-output"
          test-args: "--nogpu -j4"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: macos-arm64-cpu-output
          path: macos-arm64-cpu-output/
  test-macos-arm64-gpu-m1:
    runs-on: [ macos, arm64, m1 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          out-dir: "macos-arm64-gpu-m1-output"
          test-args: "--device M1 --nocpu"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: macos-arm64-gpu-m1-output
          path: macos-arm64-gpu-m1-output/
  test-macos-x86_64-cpu:
    runs-on: [ macos, x86_64 ]
    needs:
      - build-macos-universal-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "macos-universal"
          out-dir: "macos-x86_64-cpu-output"
          test-args: "--nogpu -j4"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: macos-x86_64-cpu-output
          path: macos-x86_64-cpu-output/
  analyze-output:
    runs-on: [ linux ]
    needs: [ test-windows-x86_64-cpu, test-windows-x86_64-gpu-nv, test-windows-x86_64-gpu-amd, test-windows-x86_64-gpu-arc, test-windows-x86_64-gpu-xe, test-windows-arm64-cpu, test-windows-arm64-gpu-adreno, test-linux-x86_64-cpu, test-linux-x86_64-gpu-amd, test-linux-x86_64-gpu-nv, test-macos-arm64-cpu, test-macos-arm64-gpu-m1, test-macos-x86_64-cpu ]
    if: always()
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: scripts/analyze_output.py
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-cpu-output
          path: windows-x86_64-cpu-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gpu-nv-output
          path: windows-x86_64-gpu-nv-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gpu-amd-output
          path: windows-x86_64-gpu-amd-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gpu-arc-output
          path: windows-x86_64-gpu-arc-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gpu-xe-output
          path: windows-x86_64-gpu-xe-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-arm64-cpu-output
          path: windows-arm64-cpu-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-arm64-gpu-adreno-output
          path: windows-arm64-gpu-adreno-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-cpu-output
          path: linux-x86_64-cpu-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-gpu-amd-output
          path: linux-x86_64-gpu-amd-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-gpu-nv-output
          path: linux-x86_64-gpu-nv-output/
      - uses: actions/download-artifact@v3
        with:
          name: macos-arm64-cpu-output
          path: macos-arm64-cpu-output/
      - uses: actions/download-artifact@v3
        with:
          name: macos-arm64-gpu-m1-output
          path: macos-arm64-gpu-m1-output/
      - uses: actions/download-artifact@v3
        with:
          name: macos-x86_64-cpu-output
          path: macos-x86_64-cpu-output/
      - name: Analyze Output
        run: |
          python scripts/analyze_output.py windows-x86_64-cpu-output/test_Ray_output.txt windows-x86_64-gpu-nv-output/test_Ray_output.txt windows-x86_64-gpu-amd-output/test_Ray_output.txt windows-x86_64-gpu-arc-output/test_Ray_output.txt windows-x86_64-gpu-xe-output/test_Ray_output.txt windows-arm64-cpu-output/test_Ray_output.txt windows-arm64-gpu-adreno-output/test_Ray_output.txt linux-x86_64-cpu-output/test_Ray_output.txt linux-x86_64-gpu-amd-output/test_Ray_output.txt linux-x86_64-gpu-nv-output/test_Ray_output.txt macos-arm64-cpu-output/test_Ray_output.txt macos-arm64-gpu-m1-output/test_Ray_output.txt macos-x86_64-cpu-output/test_Ray_output.txt
        shell: bash